/**
 * generated by Xtext 2.22.0
 */
package de.cau.cs.kieler.spviz.spvizmodel.sPVizModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Connection</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Connection#getName <em>Name</em>}</li>
 *   <li>{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Connection#getDependsOn <em>Depends On</em>}</li>
 * </ul>
 *
 * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.SPVizModelPackage#getConnection()
 * @model
 * @generated
 */
public interface Connection extends Reference
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.SPVizModelPackage#getConnection_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Connection#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Depends On</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Depends On</em>' reference.
   * @see #setDependsOn(Artifact)
   * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.SPVizModelPackage#getConnection_DependsOn()
   * @model
   * @generated
   */
  Artifact getDependsOn();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Connection#getDependsOn <em>Depends On</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Depends On</em>' reference.
   * @see #getDependsOn()
   * @generated
   */
  void setDependsOn(Artifact value);

} // Connection
