/**
 * KIELER - Kiel Integrated Environment for Layout Eclipse RichClient
 * 
 * http://rtsys.informatik.uni-kiel.de/kieler
 * 
 * Copyright 2021 by
 * + Kiel University
 *   + Department of Computer Science
 *     + Real-Time and Embedded Systems Group
 * 
 * Generated by Xtext 2.25.0
 * 
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 * 
 * SPDX-License-Identifier: EPL-2.0
 */
package de.cau.cs.kieler.spviz.spvizmodel.sPVizModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Containment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Containment#getContains <em>Contains</em>}</li>
 * </ul>
 *
 * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.SPVizModelPackage#getContainment()
 * @model
 * @generated
 */
public interface Containment extends Reference
{
  /**
   * Returns the value of the '<em><b>Contains</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contains</em>' reference.
   * @see #setContains(Artifact)
   * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.SPVizModelPackage#getContainment_Contains()
   * @model
   * @generated
   */
  Artifact getContains();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Containment#getContains <em>Contains</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Contains</em>' reference.
   * @see #getContains()
   * @generated
   */
  void setContains(Artifact value);

} // Containment
