/**
 * generated by Xtext 2.22.0
 */
package de.cau.cs.kieler.spviz.spvizmodel.sPVizModel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.SPVizModelPackage#getReference()
 * @model
 * @generated
 */
public interface Reference extends EObject
{
} // Reference
