/**
 * generated by Xtext 2.22.0
 */
package de.cau.cs.kieler.spviz.spvizmodel.sPVizModel;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.SPVizModelFactory
 * @model kind="package"
 * @generated
 */
public interface SPVizModelPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "sPVizModel";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.cau.de/cs/kieler/spviz/spvizmodel/SPVizModel";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "sPVizModel";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SPVizModelPackage eINSTANCE = de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.SPVizModelPackageImpl.init();

  /**
   * The meta object id for the '{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.SPVizModelImpl <em>SP Viz Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.SPVizModelImpl
   * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.SPVizModelPackageImpl#getSPVizModel()
   * @generated
   */
  int SP_VIZ_MODEL = 0;

  /**
   * The feature id for the '<em><b>Package</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SP_VIZ_MODEL__PACKAGE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SP_VIZ_MODEL__NAME = 1;

  /**
   * The feature id for the '<em><b>Artifacts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SP_VIZ_MODEL__ARTIFACTS = 2;

  /**
   * The number of structural features of the '<em>SP Viz Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SP_VIZ_MODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.ArtifactImpl <em>Artifact</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.ArtifactImpl
   * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.SPVizModelPackageImpl#getArtifact()
   * @generated
   */
  int ARTIFACT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARTIFACT__NAME = 0;

  /**
   * The feature id for the '<em><b>References</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARTIFACT__REFERENCES = 1;

  /**
   * The number of structural features of the '<em>Artifact</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARTIFACT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.ReferenceImpl <em>Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.ReferenceImpl
   * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.SPVizModelPackageImpl#getReference()
   * @generated
   */
  int REFERENCE = 2;

  /**
   * The number of structural features of the '<em>Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.ContainmentImpl <em>Containment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.ContainmentImpl
   * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.SPVizModelPackageImpl#getContainment()
   * @generated
   */
  int CONTAINMENT = 3;

  /**
   * The feature id for the '<em><b>Contains</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINMENT__CONTAINS = REFERENCE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Containment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINMENT_FEATURE_COUNT = REFERENCE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.ConnectionImpl <em>Connection</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.ConnectionImpl
   * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.SPVizModelPackageImpl#getConnection()
   * @generated
   */
  int CONNECTION = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION__NAME = REFERENCE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Depends On</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION__DEPENDS_ON = REFERENCE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Connection</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION_FEATURE_COUNT = REFERENCE_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.SPVizModel <em>SP Viz Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SP Viz Model</em>'.
   * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.SPVizModel
   * @generated
   */
  EClass getSPVizModel();

  /**
   * Returns the meta object for the attribute '{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.SPVizModel#getPackage <em>Package</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Package</em>'.
   * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.SPVizModel#getPackage()
   * @see #getSPVizModel()
   * @generated
   */
  EAttribute getSPVizModel_Package();

  /**
   * Returns the meta object for the attribute '{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.SPVizModel#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.SPVizModel#getName()
   * @see #getSPVizModel()
   * @generated
   */
  EAttribute getSPVizModel_Name();

  /**
   * Returns the meta object for the containment reference list '{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.SPVizModel#getArtifacts <em>Artifacts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Artifacts</em>'.
   * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.SPVizModel#getArtifacts()
   * @see #getSPVizModel()
   * @generated
   */
  EReference getSPVizModel_Artifacts();

  /**
   * Returns the meta object for class '{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Artifact <em>Artifact</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Artifact</em>'.
   * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Artifact
   * @generated
   */
  EClass getArtifact();

  /**
   * Returns the meta object for the attribute '{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Artifact#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Artifact#getName()
   * @see #getArtifact()
   * @generated
   */
  EAttribute getArtifact_Name();

  /**
   * Returns the meta object for the containment reference list '{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Artifact#getReferences <em>References</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>References</em>'.
   * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Artifact#getReferences()
   * @see #getArtifact()
   * @generated
   */
  EReference getArtifact_References();

  /**
   * Returns the meta object for class '{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Reference <em>Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Reference</em>'.
   * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Reference
   * @generated
   */
  EClass getReference();

  /**
   * Returns the meta object for class '{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Containment <em>Containment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Containment</em>'.
   * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Containment
   * @generated
   */
  EClass getContainment();

  /**
   * Returns the meta object for the reference '{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Containment#getContains <em>Contains</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Contains</em>'.
   * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Containment#getContains()
   * @see #getContainment()
   * @generated
   */
  EReference getContainment_Contains();

  /**
   * Returns the meta object for class '{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Connection <em>Connection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Connection</em>'.
   * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Connection
   * @generated
   */
  EClass getConnection();

  /**
   * Returns the meta object for the attribute '{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Connection#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Connection#getName()
   * @see #getConnection()
   * @generated
   */
  EAttribute getConnection_Name();

  /**
   * Returns the meta object for the reference '{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Connection#getDependsOn <em>Depends On</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Depends On</em>'.
   * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Connection#getDependsOn()
   * @see #getConnection()
   * @generated
   */
  EReference getConnection_DependsOn();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SPVizModelFactory getSPVizModelFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.SPVizModelImpl <em>SP Viz Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.SPVizModelImpl
     * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.SPVizModelPackageImpl#getSPVizModel()
     * @generated
     */
    EClass SP_VIZ_MODEL = eINSTANCE.getSPVizModel();

    /**
     * The meta object literal for the '<em><b>Package</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SP_VIZ_MODEL__PACKAGE = eINSTANCE.getSPVizModel_Package();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SP_VIZ_MODEL__NAME = eINSTANCE.getSPVizModel_Name();

    /**
     * The meta object literal for the '<em><b>Artifacts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SP_VIZ_MODEL__ARTIFACTS = eINSTANCE.getSPVizModel_Artifacts();

    /**
     * The meta object literal for the '{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.ArtifactImpl <em>Artifact</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.ArtifactImpl
     * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.SPVizModelPackageImpl#getArtifact()
     * @generated
     */
    EClass ARTIFACT = eINSTANCE.getArtifact();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARTIFACT__NAME = eINSTANCE.getArtifact_Name();

    /**
     * The meta object literal for the '<em><b>References</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARTIFACT__REFERENCES = eINSTANCE.getArtifact_References();

    /**
     * The meta object literal for the '{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.ReferenceImpl <em>Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.ReferenceImpl
     * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.SPVizModelPackageImpl#getReference()
     * @generated
     */
    EClass REFERENCE = eINSTANCE.getReference();

    /**
     * The meta object literal for the '{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.ContainmentImpl <em>Containment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.ContainmentImpl
     * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.SPVizModelPackageImpl#getContainment()
     * @generated
     */
    EClass CONTAINMENT = eINSTANCE.getContainment();

    /**
     * The meta object literal for the '<em><b>Contains</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTAINMENT__CONTAINS = eINSTANCE.getContainment_Contains();

    /**
     * The meta object literal for the '{@link de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.ConnectionImpl <em>Connection</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.ConnectionImpl
     * @see de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.impl.SPVizModelPackageImpl#getConnection()
     * @generated
     */
    EClass CONNECTION = eINSTANCE.getConnection();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONNECTION__NAME = eINSTANCE.getConnection_Name();

    /**
     * The meta object literal for the '<em><b>Depends On</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONNECTION__DEPENDS_ON = eINSTANCE.getConnection_DependsOn();

  }

} //SPVizModelPackage
