/**
 * KIELER - Kiel Integrated Environment for Layout Eclipse RichClient
 * 
 * http://rtsys.informatik.uni-kiel.de/kieler
 * 
 * Copyright 2023 by
 * + Kiel University
 *   + Department of Computer Science
 *     + Real-Time and Embedded Systems Group
 * 
 * Generated by Xtext 2.27.0
 * 
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 * 
 * SPDX-License-Identifier: EPL-2.0
 */
package de.cau.cs.kieler.spviz.spviz.sPViz;

import de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Artifact;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Artifact Chain</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.cau.cs.kieler.spviz.spviz.sPViz.ArtifactChain#getSource <em>Source</em>}</li>
 *   <li>{@link de.cau.cs.kieler.spviz.spviz.sPViz.ArtifactChain#getFurther <em>Further</em>}</li>
 * </ul>
 *
 * @see de.cau.cs.kieler.spviz.spviz.sPViz.SPVizPackage#getArtifactChain()
 * @model
 * @generated
 */
public interface ArtifactChain extends EObject
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' reference.
   * @see #setSource(Artifact)
   * @see de.cau.cs.kieler.spviz.spviz.sPViz.SPVizPackage#getArtifactChain_Source()
   * @model
   * @generated
   */
  Artifact getSource();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.spviz.spviz.sPViz.ArtifactChain#getSource <em>Source</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' reference.
   * @see #getSource()
   * @generated
   */
  void setSource(Artifact value);

  /**
   * Returns the value of the '<em><b>Further</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Further</em>' containment reference.
   * @see #setFurther(ArtifactChain)
   * @see de.cau.cs.kieler.spviz.spviz.sPViz.SPVizPackage#getArtifactChain_Further()
   * @model containment="true"
   * @generated
   */
  ArtifactChain getFurther();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.spviz.spviz.sPViz.ArtifactChain#getFurther <em>Further</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Further</em>' containment reference.
   * @see #getFurther()
   * @generated
   */
  void setFurther(ArtifactChain value);

} // ArtifactChain
