/**
 * KIELER - Kiel Integrated Environment for Layout Eclipse RichClient
 * 
 * http://rtsys.informatik.uni-kiel.de/kieler
 * 
 * Copyright 2022 by
 * + Kiel University
 *   + Department of Computer Science
 *     + Real-Time and Embedded Systems Group
 * 
 * Generated by Xtext 2.25.0
 * 
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 * 
 * SPDX-License-Identifier: EPL-2.0
 */
package de.cau.cs.kieler.spviz.spviz.sPViz;

import de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Artifact;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Artifact Source</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.cau.cs.kieler.spviz.spviz.sPViz.ArtifactSource#getArtifact <em>Artifact</em>}</li>
 *   <li>{@link de.cau.cs.kieler.spviz.spviz.sPViz.ArtifactSource#getSourceChain <em>Source Chain</em>}</li>
 * </ul>
 *
 * @see de.cau.cs.kieler.spviz.spviz.sPViz.SPVizPackage#getArtifactSource()
 * @model
 * @generated
 */
public interface ArtifactSource extends EObject
{
  /**
   * Returns the value of the '<em><b>Artifact</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Artifact</em>' reference.
   * @see #setArtifact(Artifact)
   * @see de.cau.cs.kieler.spviz.spviz.sPViz.SPVizPackage#getArtifactSource_Artifact()
   * @model
   * @generated
   */
  Artifact getArtifact();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.spviz.spviz.sPViz.ArtifactSource#getArtifact <em>Artifact</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Artifact</em>' reference.
   * @see #getArtifact()
   * @generated
   */
  void setArtifact(Artifact value);

  /**
   * Returns the value of the '<em><b>Source Chain</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source Chain</em>' containment reference.
   * @see #setSourceChain(ArtifactChain)
   * @see de.cau.cs.kieler.spviz.spviz.sPViz.SPVizPackage#getArtifactSource_SourceChain()
   * @model containment="true"
   * @generated
   */
  ArtifactChain getSourceChain();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.spviz.spviz.sPViz.ArtifactSource#getSourceChain <em>Source Chain</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source Chain</em>' containment reference.
   * @see #getSourceChain()
   * @generated
   */
  void setSourceChain(ArtifactChain value);

} // ArtifactSource
