/**
 * generated by Xtext 2.22.0
 */
package de.cau.cs.kieler.spviz.spviz.sPViz;

import de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Artifact;
import de.cau.cs.kieler.spviz.spvizmodel.sPVizModel.Connection;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Shown Connection</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.cau.cs.kieler.spviz.spviz.sPViz.ShownConnection#getShownConnection <em>Shown Connection</em>}</li>
 *   <li>{@link de.cau.cs.kieler.spviz.spviz.sPViz.ShownConnection#getVia <em>Via</em>}</li>
 * </ul>
 *
 * @see de.cau.cs.kieler.spviz.spviz.sPViz.SPVizPackage#getShownConnection()
 * @model
 * @generated
 */
public interface ShownConnection extends EObject
{
  /**
   * Returns the value of the '<em><b>Shown Connection</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Shown Connection</em>' reference.
   * @see #setShownConnection(Connection)
   * @see de.cau.cs.kieler.spviz.spviz.sPViz.SPVizPackage#getShownConnection_ShownConnection()
   * @model
   * @generated
   */
  Connection getShownConnection();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.spviz.spviz.sPViz.ShownConnection#getShownConnection <em>Shown Connection</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Shown Connection</em>' reference.
   * @see #getShownConnection()
   * @generated
   */
  void setShownConnection(Connection value);

  /**
   * Returns the value of the '<em><b>Via</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Via</em>' reference.
   * @see #setVia(Artifact)
   * @see de.cau.cs.kieler.spviz.spviz.sPViz.SPVizPackage#getShownConnection_Via()
   * @model
   * @generated
   */
  Artifact getVia();

  /**
   * Sets the value of the '{@link de.cau.cs.kieler.spviz.spviz.sPViz.ShownConnection#getVia <em>Via</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Via</em>' reference.
   * @see #getVia()
   * @generated
   */
  void setVia(Artifact value);

} // ShownConnection
