/**
 * KIELER - Kiel Integrated Environment for Layout Eclipse RichClient
 * 
 * http://rtsys.informatik.uni-kiel.de/kieler
 * 
 * Copyright 2023 by
 * + Kiel University
 *   + Department of Computer Science
 *     + Real-Time and Embedded Systems Group
 * 
 * Generated by Xtext 2.27.0
 * 
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 * 
 * SPDX-License-Identifier: EPL-2.0
 */
package de.cau.cs.kieler.spviz.spviz.sPViz;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see de.cau.cs.kieler.spviz.spviz.sPViz.SPVizPackage
 * @generated
 */
public interface SPVizFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SPVizFactory eINSTANCE = de.cau.cs.kieler.spviz.spviz.sPViz.impl.SPVizFactoryImpl.init();

  /**
   * Returns a new object of class '<em>SP Viz</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>SP Viz</em>'.
   * @generated
   */
  SPViz createSPViz();

  /**
   * Returns a new object of class '<em>View</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>View</em>'.
   * @generated
   */
  View createView();

  /**
   * Returns a new object of class '<em>Artifact Shows</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Artifact Shows</em>'.
   * @generated
   */
  ArtifactShows createArtifactShows();

  /**
   * Returns a new object of class '<em>Artifact View</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Artifact View</em>'.
   * @generated
   */
  ArtifactView createArtifactView();

  /**
   * Returns a new object of class '<em>Artifact Source</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Artifact Source</em>'.
   * @generated
   */
  ArtifactSource createArtifactSource();

  /**
   * Returns a new object of class '<em>Artifact Chain</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Artifact Chain</em>'.
   * @generated
   */
  ArtifactChain createArtifactChain();

  /**
   * Returns a new object of class '<em>Shown Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Shown Element</em>'.
   * @generated
   */
  ShownElement createShownElement();

  /**
   * Returns a new object of class '<em>Shown Connection</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Shown Connection</em>'.
   * @generated
   */
  ShownConnection createShownConnection();

  /**
   * Returns a new object of class '<em>Shown Category Connection</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Shown Category Connection</em>'.
   * @generated
   */
  ShownCategoryConnection createShownCategoryConnection();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  SPVizPackage getSPVizPackage();

} //SPVizFactory
