/*
 * generated by Xtext 2.22.0
 */
package de.cau.cs.kieler.spviz.spviz.ui.tests;

import com.google.inject.Injector;
import de.cau.cs.kieler.spviz.spviz.ui.internal.SpvizActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class SPVizUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SpvizActivator.getInstance().getInjector("de.cau.cs.kieler.spviz.spviz.SPViz");
	}

}
