/*
 * KIELER - Kiel Integrated Environment for Layout Eclipse RichClient
 *
 * http://rtsys.informatik.uni-kiel.de/kieler
 * 
 * Copyright 2023 by
 * + Kiel University
 *   + Department of Computer Science
 *     + Real-Time and Embedded Systems Group
 *
 * Generated by Xtext 2.27.0
 * 
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 * 
 * SPDX-License-Identifier: EPL-2.0
 */
package de.cau.cs.kieler.spviz.spviz.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SPVizGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class SPVizElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.cau.cs.kieler.spviz.spviz.SPViz.SPViz");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPackageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cPackageAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPackageQualifiedNameParserRuleCall_1_0 = (RuleCall)cPackageAssignment_1.eContents().get(0);
		private final Keyword cImportKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cImportURIAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cImportURISTRINGTerminalRuleCall_3_0 = (RuleCall)cImportURIAssignment_3.eContents().get(0);
		private final Keyword cSPVizKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cNameAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cNameIDTerminalRuleCall_5_0 = (RuleCall)cNameAssignment_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cViewsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cViewsViewParserRuleCall_7_0 = (RuleCall)cViewsAssignment_7.eContents().get(0);
		private final Assignment cArtifactShowsAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cArtifactShowsArtifactShowsParserRuleCall_8_0 = (RuleCall)cArtifactShowsAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//SPViz:
		//    'package' package=QualifiedName
		//    'import' importURI=STRING
		//    'SPViz' name=ID '{'
		//        views += View*
		//        artifactShows += ArtifactShows*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'package' package=QualifiedName
		//'import' importURI=STRING
		//'SPViz' name=ID '{'
		//    views += View*
		//    artifactShows += ArtifactShows*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'package'
		public Keyword getPackageKeyword_0() { return cPackageKeyword_0; }
		
		//package=QualifiedName
		public Assignment getPackageAssignment_1() { return cPackageAssignment_1; }
		
		//QualifiedName
		public RuleCall getPackageQualifiedNameParserRuleCall_1_0() { return cPackageQualifiedNameParserRuleCall_1_0; }
		
		//'import'
		public Keyword getImportKeyword_2() { return cImportKeyword_2; }
		
		//importURI=STRING
		public Assignment getImportURIAssignment_3() { return cImportURIAssignment_3; }
		
		//STRING
		public RuleCall getImportURISTRINGTerminalRuleCall_3_0() { return cImportURISTRINGTerminalRuleCall_3_0; }
		
		//'SPViz'
		public Keyword getSPVizKeyword_4() { return cSPVizKeyword_4; }
		
		//name=ID
		public Assignment getNameAssignment_5() { return cNameAssignment_5; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_5_0() { return cNameIDTerminalRuleCall_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }
		
		//views += View*
		public Assignment getViewsAssignment_7() { return cViewsAssignment_7; }
		
		//View
		public RuleCall getViewsViewParserRuleCall_7_0() { return cViewsViewParserRuleCall_7_0; }
		
		//artifactShows += ArtifactShows*
		public Assignment getArtifactShowsAssignment_8() { return cArtifactShowsAssignment_8; }
		
		//ArtifactShows
		public RuleCall getArtifactShowsArtifactShowsParserRuleCall_8_0() { return cArtifactShowsArtifactShowsParserRuleCall_8_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class ViewElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.cau.cs.kieler.spviz.spviz.SPViz.View");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cShownElementsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cShownElementsShownElementParserRuleCall_2_0 = (RuleCall)cShownElementsAssignment_2.eContents().get(0);
		private final Assignment cShownConnectionsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cShownConnectionsShownConnectionParserRuleCall_3_0 = (RuleCall)cShownConnectionsAssignment_3.eContents().get(0);
		private final Assignment cShownCategoryConnectionsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cShownCategoryConnectionsShownCategoryConnectionParserRuleCall_4_0 = (RuleCall)cShownCategoryConnectionsAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//View:
		//    name=ID '{'
		//        (shownElements+=ShownElement)*
		//        (shownConnections+=ShownConnection)*
		//        (shownCategoryConnections+=ShownCategoryConnection)*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID '{'
		//    (shownElements+=ShownElement)*
		//    (shownConnections+=ShownConnection)*
		//    (shownCategoryConnections+=ShownCategoryConnection)*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//(shownElements+=ShownElement)*
		public Assignment getShownElementsAssignment_2() { return cShownElementsAssignment_2; }
		
		//ShownElement
		public RuleCall getShownElementsShownElementParserRuleCall_2_0() { return cShownElementsShownElementParserRuleCall_2_0; }
		
		//(shownConnections+=ShownConnection)*
		public Assignment getShownConnectionsAssignment_3() { return cShownConnectionsAssignment_3; }
		
		//ShownConnection
		public RuleCall getShownConnectionsShownConnectionParserRuleCall_3_0() { return cShownConnectionsShownConnectionParserRuleCall_3_0; }
		
		//(shownCategoryConnections+=ShownCategoryConnection)*
		public Assignment getShownCategoryConnectionsAssignment_4() { return cShownCategoryConnectionsAssignment_4; }
		
		//ShownCategoryConnection
		public RuleCall getShownCategoryConnectionsShownCategoryConnectionParserRuleCall_4_0() { return cShownCategoryConnectionsShownCategoryConnectionParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ArtifactShowsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.cau.cs.kieler.spviz.spviz.SPViz.ArtifactShows");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cArtifactShowsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cArtifactShowsArtifactCrossReference_0_0 = (CrossReference)cArtifactShowsAssignment_0.eContents().get(0);
		private final RuleCall cArtifactShowsArtifactQualifiedNameParserRuleCall_0_0_1 = (RuleCall)cArtifactShowsArtifactCrossReference_0_0.eContents().get(1);
		private final Keyword cShowsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cViewsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cViewsArtifactViewParserRuleCall_3_0 = (RuleCall)cViewsAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//ArtifactShows:
		//    artifactShows=[spvizmodel::Artifact|QualifiedName] 'shows' '{'
		//        views += ArtifactView*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//artifactShows=[spvizmodel::Artifact|QualifiedName] 'shows' '{'
		//    views += ArtifactView*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//artifactShows=[spvizmodel::Artifact|QualifiedName]
		public Assignment getArtifactShowsAssignment_0() { return cArtifactShowsAssignment_0; }
		
		//[spvizmodel::Artifact|QualifiedName]
		public CrossReference getArtifactShowsArtifactCrossReference_0_0() { return cArtifactShowsArtifactCrossReference_0_0; }
		
		//QualifiedName
		public RuleCall getArtifactShowsArtifactQualifiedNameParserRuleCall_0_0_1() { return cArtifactShowsArtifactQualifiedNameParserRuleCall_0_0_1; }
		
		//'shows'
		public Keyword getShowsKeyword_1() { return cShowsKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//views += ArtifactView*
		public Assignment getViewsAssignment_3() { return cViewsAssignment_3; }
		
		//ArtifactView
		public RuleCall getViewsArtifactViewParserRuleCall_3_0() { return cViewsArtifactViewParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ArtifactViewElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.cau.cs.kieler.spviz.spviz.SPViz.ArtifactView");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cViewAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cViewViewCrossReference_0_0 = (CrossReference)cViewAssignment_0.eContents().get(0);
		private final RuleCall cViewViewIDTerminalRuleCall_0_0_1 = (RuleCall)cViewViewCrossReference_0_0.eContents().get(1);
		private final Keyword cWithKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSourcesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSourcesArtifactSourceParserRuleCall_3_0 = (RuleCall)cSourcesAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//ArtifactView:
		//    view = [View] 'with' '{'
		//        sources += ArtifactSource*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//view = [View] 'with' '{'
		//    sources += ArtifactSource*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//view = [View]
		public Assignment getViewAssignment_0() { return cViewAssignment_0; }
		
		//[View]
		public CrossReference getViewViewCrossReference_0_0() { return cViewViewCrossReference_0_0; }
		
		//ID
		public RuleCall getViewViewIDTerminalRuleCall_0_0_1() { return cViewViewIDTerminalRuleCall_0_0_1; }
		
		//'with'
		public Keyword getWithKeyword_1() { return cWithKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//sources += ArtifactSource*
		public Assignment getSourcesAssignment_3() { return cSourcesAssignment_3; }
		
		//ArtifactSource
		public RuleCall getSourcesArtifactSourceParserRuleCall_3_0() { return cSourcesArtifactSourceParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ArtifactSourceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.cau.cs.kieler.spviz.spviz.SPViz.ArtifactSource");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cArtifactAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cArtifactArtifactCrossReference_0_0 = (CrossReference)cArtifactAssignment_0.eContents().get(0);
		private final RuleCall cArtifactArtifactQualifiedNameParserRuleCall_0_0_1 = (RuleCall)cArtifactArtifactCrossReference_0_0.eContents().get(1);
		private final Keyword cFromKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cSourceChainAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSourceChainArtifactChainParserRuleCall_2_0 = (RuleCall)cSourceChainAssignment_2.eContents().get(0);
		
		//ArtifactSource:
		//    artifact = [spvizmodel::Artifact|QualifiedName]
		//    'from' sourceChain = ArtifactChain
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//artifact = [spvizmodel::Artifact|QualifiedName]
		//'from' sourceChain = ArtifactChain
		public Group getGroup() { return cGroup; }
		
		//artifact = [spvizmodel::Artifact|QualifiedName]
		public Assignment getArtifactAssignment_0() { return cArtifactAssignment_0; }
		
		//[spvizmodel::Artifact|QualifiedName]
		public CrossReference getArtifactArtifactCrossReference_0_0() { return cArtifactArtifactCrossReference_0_0; }
		
		//QualifiedName
		public RuleCall getArtifactArtifactQualifiedNameParserRuleCall_0_0_1() { return cArtifactArtifactQualifiedNameParserRuleCall_0_0_1; }
		
		//'from'
		public Keyword getFromKeyword_1() { return cFromKeyword_1; }
		
		//sourceChain = ArtifactChain
		public Assignment getSourceChainAssignment_2() { return cSourceChainAssignment_2; }
		
		//ArtifactChain
		public RuleCall getSourceChainArtifactChainParserRuleCall_2_0() { return cSourceChainArtifactChainParserRuleCall_2_0; }
	}
	public class ArtifactChainElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.cau.cs.kieler.spviz.spviz.SPViz.ArtifactChain");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cSourceAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cSourceArtifactCrossReference_0_0 = (CrossReference)cSourceAssignment_0.eContents().get(0);
		private final RuleCall cSourceArtifactQualifiedNameParserRuleCall_0_0_1 = (RuleCall)cSourceArtifactCrossReference_0_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cGreaterThanSignKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cFurtherAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cFurtherArtifactChainParserRuleCall_1_1_0 = (RuleCall)cFurtherAssignment_1_1.eContents().get(0);
		
		//ArtifactChain:
		//    source = [spvizmodel::Artifact|QualifiedName] ('>' further = ArtifactChain)?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//source = [spvizmodel::Artifact|QualifiedName] ('>' further = ArtifactChain)?
		public Group getGroup() { return cGroup; }
		
		//source = [spvizmodel::Artifact|QualifiedName]
		public Assignment getSourceAssignment_0() { return cSourceAssignment_0; }
		
		//[spvizmodel::Artifact|QualifiedName]
		public CrossReference getSourceArtifactCrossReference_0_0() { return cSourceArtifactCrossReference_0_0; }
		
		//QualifiedName
		public RuleCall getSourceArtifactQualifiedNameParserRuleCall_0_0_1() { return cSourceArtifactQualifiedNameParserRuleCall_0_0_1; }
		
		//('>' further = ArtifactChain)?
		public Group getGroup_1() { return cGroup_1; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_1_0() { return cGreaterThanSignKeyword_1_0; }
		
		//further = ArtifactChain
		public Assignment getFurtherAssignment_1_1() { return cFurtherAssignment_1_1; }
		
		//ArtifactChain
		public RuleCall getFurtherArtifactChainParserRuleCall_1_1_0() { return cFurtherArtifactChainParserRuleCall_1_1_0; }
	}
	public class ShownElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.cau.cs.kieler.spviz.spviz.SPViz.ShownElement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cShowKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cShownElementAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cShownElementArtifactCrossReference_1_0 = (CrossReference)cShownElementAssignment_1.eContents().get(0);
		private final RuleCall cShownElementArtifactQualifiedNameParserRuleCall_1_0_1 = (RuleCall)cShownElementArtifactCrossReference_1_0.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cInKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cContainedInAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final CrossReference cContainedInArtifactCrossReference_2_1_0 = (CrossReference)cContainedInAssignment_2_1.eContents().get(0);
		private final RuleCall cContainedInArtifactQualifiedNameParserRuleCall_2_1_0_1 = (RuleCall)cContainedInArtifactCrossReference_2_1_0.eContents().get(1);
		
		//ShownElement:
		//    'show' shownElement=[spvizmodel::Artifact|QualifiedName]
		//    (
		//        'in' containedIn=[spvizmodel::Artifact|QualifiedName]
		//    )?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'show' shownElement=[spvizmodel::Artifact|QualifiedName]
		//(
		//    'in' containedIn=[spvizmodel::Artifact|QualifiedName]
		//)?
		public Group getGroup() { return cGroup; }
		
		//'show'
		public Keyword getShowKeyword_0() { return cShowKeyword_0; }
		
		//shownElement=[spvizmodel::Artifact|QualifiedName]
		public Assignment getShownElementAssignment_1() { return cShownElementAssignment_1; }
		
		//[spvizmodel::Artifact|QualifiedName]
		public CrossReference getShownElementArtifactCrossReference_1_0() { return cShownElementArtifactCrossReference_1_0; }
		
		//QualifiedName
		public RuleCall getShownElementArtifactQualifiedNameParserRuleCall_1_0_1() { return cShownElementArtifactQualifiedNameParserRuleCall_1_0_1; }
		
		//(
		//    'in' containedIn=[spvizmodel::Artifact|QualifiedName]
		//)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'in'
		public Keyword getInKeyword_2_0() { return cInKeyword_2_0; }
		
		//containedIn=[spvizmodel::Artifact|QualifiedName]
		public Assignment getContainedInAssignment_2_1() { return cContainedInAssignment_2_1; }
		
		//[spvizmodel::Artifact|QualifiedName]
		public CrossReference getContainedInArtifactCrossReference_2_1_0() { return cContainedInArtifactCrossReference_2_1_0; }
		
		//QualifiedName
		public RuleCall getContainedInArtifactQualifiedNameParserRuleCall_2_1_0_1() { return cContainedInArtifactQualifiedNameParserRuleCall_2_1_0_1; }
	}
	public class ShownConnectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.cau.cs.kieler.spviz.spviz.SPViz.ShownConnection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cConnectKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cShownConnectionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cShownConnectionConnectionCrossReference_1_0 = (CrossReference)cShownConnectionAssignment_1.eContents().get(0);
		private final RuleCall cShownConnectionConnectionQualifiedNameParserRuleCall_1_0_1 = (RuleCall)cShownConnectionConnectionCrossReference_1_0.eContents().get(1);
		
		//ShownConnection:
		//    'connect' shownConnection=[spvizmodel::Connection|QualifiedName]
		////    (
		////        'via' via=[spvizmodel::Artifact|QualifiedName]
		////    )?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'connect' shownConnection=[spvizmodel::Connection|QualifiedName]
		public Group getGroup() { return cGroup; }
		
		//'connect'
		public Keyword getConnectKeyword_0() { return cConnectKeyword_0; }
		
		//shownConnection=[spvizmodel::Connection|QualifiedName]
		public Assignment getShownConnectionAssignment_1() { return cShownConnectionAssignment_1; }
		
		//[spvizmodel::Connection|QualifiedName]
		public CrossReference getShownConnectionConnectionCrossReference_1_0() { return cShownConnectionConnectionCrossReference_1_0; }
		
		//QualifiedName
		public RuleCall getShownConnectionConnectionQualifiedNameParserRuleCall_1_0_1() { return cShownConnectionConnectionQualifiedNameParserRuleCall_1_0_1; }
	}
	public class ShownCategoryConnectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.cau.cs.kieler.spviz.spviz.SPViz.ShownCategoryConnection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cConnectKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cConnectionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cConnectionConnectionCrossReference_1_0 = (CrossReference)cConnectionAssignment_1.eContents().get(0);
		private final RuleCall cConnectionConnectionQualifiedNameParserRuleCall_1_0_1 = (RuleCall)cConnectionConnectionCrossReference_1_0.eContents().get(1);
		private final Keyword cViaKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSourceChainAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSourceChainArtifactChainParserRuleCall_3_0 = (RuleCall)cSourceChainAssignment_3.eContents().get(0);
		
		//ShownCategoryConnection:
		//    'connect' connection=[spvizmodel::Connection|QualifiedName]
		//    'via' sourceChain=ArtifactChain
		//    // TODO: we may need an alternative syntax for category connections, where the source/target element is not clear,
		//    // e.g. by writing connect Feature to Feature via source Feature>Bundle and target Feature>Bundle and connection Dependency
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'connect' connection=[spvizmodel::Connection|QualifiedName]
		//'via' sourceChain=ArtifactChain
		public Group getGroup() { return cGroup; }
		
		//'connect'
		public Keyword getConnectKeyword_0() { return cConnectKeyword_0; }
		
		//connection=[spvizmodel::Connection|QualifiedName]
		public Assignment getConnectionAssignment_1() { return cConnectionAssignment_1; }
		
		//[spvizmodel::Connection|QualifiedName]
		public CrossReference getConnectionConnectionCrossReference_1_0() { return cConnectionConnectionCrossReference_1_0; }
		
		//QualifiedName
		public RuleCall getConnectionConnectionQualifiedNameParserRuleCall_1_0_1() { return cConnectionConnectionQualifiedNameParserRuleCall_1_0_1; }
		
		//'via'
		public Keyword getViaKeyword_2() { return cViaKeyword_2; }
		
		//sourceChain=ArtifactChain
		public Assignment getSourceChainAssignment_3() { return cSourceChainAssignment_3; }
		
		//ArtifactChain
		public RuleCall getSourceChainArtifactChainParserRuleCall_3_0() { return cSourceChainArtifactChainParserRuleCall_3_0; }
	}
	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.cau.cs.kieler.spviz.spviz.SPViz.QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//    ID ('.' ID)*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//ID ('.' ID)*
		public Group getGroup() { return cGroup; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//('.' ID)*
		public Group getGroup_1() { return cGroup_1; }
		
		//'.'
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	
	
	private final SPVizElements pSPViz;
	private final ViewElements pView;
	private final ArtifactShowsElements pArtifactShows;
	private final ArtifactViewElements pArtifactView;
	private final ArtifactSourceElements pArtifactSource;
	private final ArtifactChainElements pArtifactChain;
	private final ShownElementElements pShownElement;
	private final ShownConnectionElements pShownConnection;
	private final ShownCategoryConnectionElements pShownCategoryConnection;
	private final QualifiedNameElements pQualifiedName;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SPVizGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pSPViz = new SPVizElements();
		this.pView = new ViewElements();
		this.pArtifactShows = new ArtifactShowsElements();
		this.pArtifactView = new ArtifactViewElements();
		this.pArtifactSource = new ArtifactSourceElements();
		this.pArtifactChain = new ArtifactChainElements();
		this.pShownElement = new ShownElementElements();
		this.pShownConnection = new ShownConnectionElements();
		this.pShownCategoryConnection = new ShownCategoryConnectionElements();
		this.pQualifiedName = new QualifiedNameElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.cau.cs.kieler.spviz.spviz.SPViz".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//SPViz:
	//    'package' package=QualifiedName
	//    'import' importURI=STRING
	//    'SPViz' name=ID '{'
	//        views += View*
	//        artifactShows += ArtifactShows*
	//    '}'
	//;
	public SPVizElements getSPVizAccess() {
		return pSPViz;
	}
	
	public ParserRule getSPVizRule() {
		return getSPVizAccess().getRule();
	}
	
	//View:
	//    name=ID '{'
	//        (shownElements+=ShownElement)*
	//        (shownConnections+=ShownConnection)*
	//        (shownCategoryConnections+=ShownCategoryConnection)*
	//    '}'
	//;
	public ViewElements getViewAccess() {
		return pView;
	}
	
	public ParserRule getViewRule() {
		return getViewAccess().getRule();
	}
	
	//ArtifactShows:
	//    artifactShows=[spvizmodel::Artifact|QualifiedName] 'shows' '{'
	//        views += ArtifactView*
	//    '}'
	//;
	public ArtifactShowsElements getArtifactShowsAccess() {
		return pArtifactShows;
	}
	
	public ParserRule getArtifactShowsRule() {
		return getArtifactShowsAccess().getRule();
	}
	
	//ArtifactView:
	//    view = [View] 'with' '{'
	//        sources += ArtifactSource*
	//    '}'
	//;
	public ArtifactViewElements getArtifactViewAccess() {
		return pArtifactView;
	}
	
	public ParserRule getArtifactViewRule() {
		return getArtifactViewAccess().getRule();
	}
	
	//ArtifactSource:
	//    artifact = [spvizmodel::Artifact|QualifiedName]
	//    'from' sourceChain = ArtifactChain
	//;
	public ArtifactSourceElements getArtifactSourceAccess() {
		return pArtifactSource;
	}
	
	public ParserRule getArtifactSourceRule() {
		return getArtifactSourceAccess().getRule();
	}
	
	//ArtifactChain:
	//    source = [spvizmodel::Artifact|QualifiedName] ('>' further = ArtifactChain)?
	//;
	public ArtifactChainElements getArtifactChainAccess() {
		return pArtifactChain;
	}
	
	public ParserRule getArtifactChainRule() {
		return getArtifactChainAccess().getRule();
	}
	
	//ShownElement:
	//    'show' shownElement=[spvizmodel::Artifact|QualifiedName]
	//    (
	//        'in' containedIn=[spvizmodel::Artifact|QualifiedName]
	//    )?
	//;
	public ShownElementElements getShownElementAccess() {
		return pShownElement;
	}
	
	public ParserRule getShownElementRule() {
		return getShownElementAccess().getRule();
	}
	
	//ShownConnection:
	//    'connect' shownConnection=[spvizmodel::Connection|QualifiedName]
	////    (
	////        'via' via=[spvizmodel::Artifact|QualifiedName]
	////    )?
	//;
	public ShownConnectionElements getShownConnectionAccess() {
		return pShownConnection;
	}
	
	public ParserRule getShownConnectionRule() {
		return getShownConnectionAccess().getRule();
	}
	
	//ShownCategoryConnection:
	//    'connect' connection=[spvizmodel::Connection|QualifiedName]
	//    'via' sourceChain=ArtifactChain
	//    // TODO: we may need an alternative syntax for category connections, where the source/target element is not clear,
	//    // e.g. by writing connect Feature to Feature via source Feature>Bundle and target Feature>Bundle and connection Dependency
	//;
	public ShownCategoryConnectionElements getShownCategoryConnectionAccess() {
		return pShownCategoryConnection;
	}
	
	public ParserRule getShownCategoryConnectionRule() {
		return getShownCategoryConnectionAccess().getRule();
	}
	
	//QualifiedName:
	//    ID ('.' ID)*
	//;
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
