/*
 * generated by Xtext 2.22.0
 */
package de.cau.cs.kieler.spviz.spvizmodel.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSPVizModelScopeProvider extends DelegatingScopeProvider {
}
