/*
 * generated by Xtext 2.22.0
 */
package de.cau.cs.kieler.spviz.spviz.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSPVizScopeProvider extends DelegatingScopeProvider {
}
