/*
 * generated by Xtext 2.22.0
 */
package de.cau.cs.kieler.spviz.spvizmodel.ui;

import com.google.inject.Injector;
import de.cau.cs.kieler.spviz.spvizmodel.ui.internal.SpvizmodelActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SPVizModelExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(SpvizmodelActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		SpvizmodelActivator activator = SpvizmodelActivator.getInstance();
		return activator != null ? activator.getInjector(SpvizmodelActivator.DE_CAU_CS_KIELER_SPVIZ_SPVIZMODEL_SPVIZMODEL) : null;
	}

}
