# Workflow that creates artifacts of the latest dev versions.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Java CI

on: 
  push:
    branches: [main]
  pull_request_target:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Cache Maven packages and distribution
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.m2/wrapper/dists
          key: ${{ runner.os }}-m2-${{ hashFiles('.github/workflows/**/*.*', '**/pom.xml', '**/META-INF/MANIFEST.MF', 'build/de.cau.cs.kieler.spviz.targetplatform/de.cau.cs.kieler.spviz.targetplatform.target') }}
      - name: Download Maven wrapper
        run: >
          mvn --batch-mode --non-recursive
          org.apache.maven.plugins:maven-wrapper-plugin:3.3.4:wrapper
          -Dmaven=3.9.16
          -Dtype=only-script
          -DdistributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.16/apache-maven-3.9.16-bin.zip
          -DdistributionSha256Sum=5af3b743dd8b876b5c45da33b676251e5f1687712644abb4ee519ca56e1d89ce
      - name: Build with Maven
        run: ./mvnw --batch-mode --update-snapshots -f build/pom.xml verify
      - name: Archive P2 Repository
        uses: actions/upload-artifact@v4
        with:
          name: SPViz P2 Repository
          path: build/de.cau.cs.kieler.spviz.repository/target/repository/**/*
          retention-days: 14
          if-no-files-found: error
      - name: Archive CLI
        uses: actions/upload-artifact@v4
        with:
          name: SPViz CLI
          path: cli/de.cau.cs.kieler.spviz.cli/target/spviz-cli.jar
          retention-days: 14
          if-no-files-found: error
