# Workflow that creates artifacts of the latest dev versions.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Java CI

on: 
  push:
    branches: [main]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: .m2
          key: ${{ runner.os }}-m2-${{ hashFiles('.github/workflows/**/*.*', '**/pom.xml', '**/META-INF/MANIFEST.MF', 'build/de.cau.cs.kieler.spviz.targetplatform/de.cau.cs.kieler.spviz.targetplatform.target') }}
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -f build/pom.xml verify
      - name: Archive P2 Repository
        uses: actions/upload-artifact@v2
        with:
          name: SPViz P2 Repository
          path: build/de.cau.cs.kieler.spviz.repository/target/repository/**/*
          retention-days: 14
          if-no-files-found: error
