# Workflow that attaches the P2 update site asset to the new release.
# Does not handle hosting the P2 update site to be used by Eclipse directly.

name: release

on:
    release:
        types: [published]

jobs:
    release-assets:
        name: "Add assets to release"
        runs-on: ubuntu-latest

        steps:
            # Build with maven
            - uses: actions/checkout@v4
            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribution: 'adopt'
            - name: Cache Maven packages
              uses: actions/cache@v4
              with:
                path: .m2
                key: ${{ runner.os }}-m2-${{ hashFiles('.github/workflows/**/*.*', '**/pom.xml', '**/META-INF/MANIFEST.MF', 'build/de.cau.cs.kieler.spviz.targetplatform/de.cau.cs.kieler.spviz.targetplatform.target') }}
            - name: Set release version
              run: mvn org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion="${GITHUB_REF##*/}" -f build/pom.xml
            - name: Build with Maven
              run: mvn --batch-mode --update-snapshots -f build/pom.xml verify

            - name: Release tag
              run: echo "::set-output name=SHORTENED_GITHUB_REF::${GITHUB_REF##*/}"
              id: release-tag
            # Upload update site zip to release
            # Github has no official action for this. Uses: https://github.com/JasonEtco/upload-to-release
            - name: Upload P2 Repository
              uses: JasonEtco/upload-to-release@d648f1babf776de9cad881320bd9e9818fc3b262
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  args: "build/de.cau.cs.kieler.spviz.repository/target/de.cau.cs.kieler.spviz.repository-${{ steps.release-tag.outputs.SHORTENED_GITHUB_REF }}.zip application/zip"